name: Sync Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Clone upstream
        run: ./scripts/bootstrap.sh
      - name: Check upstream revision
        id: gate
        run: ./scripts/check-upstream.sh
      - name: Build package
        if: steps.gate.outputs.changed == 'true'
        run: ./scripts/build.sh
      - name: Publish artifacts
        if: steps.gate.outputs.changed == 'true'
        run: ./scripts/publish.sh
      - name: Commit changes
        if: steps.gate.outputs.changed == 'true'
        run: ./scripts/commit.sh
